### ISSUE TITLE
do I have rights to run your software?

### ISSUE THREAD

**Issue by hussam-dh** [stanislav-web/OpenDoor#14]
Hello Sir,
you stated that:
Testing of the software on the commercial systems and organizations is prohibited!
but can I use it in my research for vulnerabilities in bug bounty programs

thanks

**Comment by stanislav-web** [comment]
Hi, Hussam. 
The application passes testing stage now, but you can use it in your case. 
This notices meaning  that using should not be harmful for third party  systems and organizations

**Comment by hussam-dh** [comment]
Thank you sir
