### ISSUE TITLE
ResponseError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by pansa** [stanislav-web/OpenDoor#17]
With -i option, subdomain scanning terminates with error :

error:   ResponseError: cannot use a string pattern on a bytes-like object                                                                           
Terminated

on page
http://beta.drweb.ru

Without -i option - no problem.

**Comment by stanislav-web** [comment]
Seems it was encoding problem...
Well, ifixed it. You can try to fetch lastest changes

**Comment by pansa** [comment]
All right now! Great!
