### ISSUE TITLE
No error message if missing httplib2 

### ISSUE THREAD

**Issue by Cole-Hudson** [stanislav-web/OpenDoor#2]
I kept getting the error that I was missing urllib3, colorama and termcolor, when I had each of them installed. Upon looking I saw that httplib2 was also needed. All thats needed is change to the error message to include httplib2 as potentially missing

**Comment by Cole-Hudson** [comment]
Never mind, close this, looks like I cloned the repo literally an hour before the change was made.

**Comment by stanislav-web** [comment]
I have fixed it before
