### ISSUE TITLE
No timeout setup in request

### ISSUE THREAD

**Issue by pansa** [stanislav-web/OpenDoor#20]
v3.4.48

In ./src/core/http/https.py  (and other like), parameter timeout not defined in "request" function:

response = PoolManager().request(self.__cfg.method, url,
                                                 headers=self._headers,
                                                 retries=self.__cfg.retries,
                                                 assert_same_host=False, 
                                                 redirect=False)

so i got totally stoped scan progress if any not-responsable domain was requested, eg 
"https://mail3.1tv.ru"

Adding timeout=3 helps me.

**Comment by stanislav-web** [comment]
Timeout is declared for whole Pool (HTTPSConnectionPool, HTTPConnectionPool, ProxyManager) and default has 30 sec
```
--timeout TIMEOUT     Request timeout (30 sec default)
``
That means that every request in the pool will be ignored after 30 (default) seconds
But I noticed that it does not work correctly, so I set the same timeout for reading
```
HTTPSConnectionPool(HOST,
                                      POST,
                                      maxsize=self.__cfg.threads,
                                      timeout=Timeout(CONNECT=self.__cfg.timeout, READ=self.__cfg.timeout),
                                      block=True)
```

**Comment by pansa** [comment]
Yes, i set --timeout parameter for 3 and waiting 2+ min, but timeout doesn't works =(

**Comment by pansa** [comment]
Hmm, method
def __https_pool(self)
with 
pool = HTTPSConnectionPool( ...

doesn't call in my case (see later)  :\

**Comment by pansa** [comment]
For 100% sure, your can run worker in the separate process fork with global timeout for whole process.

**Comment by stanislav-web** [comment]
Solved https://github.com/stanislav-web/OpenDoor/pull/50 please update application
