### ISSUE TITLE
Subdir scan terminated when incorrect domain use

### ISSUE THREAD

**Issue by pansa** [stanislav-web/OpenDoor#21]
v3.4.48

Custom subdomain list contains domain with dot - "m." , so opendoor generate incorrect url, eg:
http://m..1tv.ru

and terminate all scan process as:

[16:54:41] error:   encoding with 'idna' codec failed (UnicodeError: label empty or too long)                                                                                                      
Terminated

Add exception catch and URL/domain normalization need, i think.

**Comment by stanislav-web** [comment]
It has been resolved  [https://github.com/stanislav-web/OpenDoor/commit/56c2f0c9832fe9293757cab868f42a9ec70baad4](link)

**Comment by pansa** [comment]
Confirm fix, Stanislav. Grazie!
