### ISSUE TITLE
requirements problem

### ISSUE THREAD

**Issue by dvisan** [stanislav-web/OpenDoor#22]
when running `python3 opendoor.py --host example.com`
I get:

> [!] Several dependencies wasn't installed!
>             Please run sudo pip install -r requirements.txt 

after logging in as root and running the command above for req install, I get a message that all 3 reqs have been installed.

runnig ubuntu 17.10 x64

**Comment by stanislav-web** [comment]
Hello! 
Try running `sudo pip3 install -r requirements.txt`
This probably happened because your python3 interpreter is not installed by default
