### ISSUE TITLE
error:   PackageError: str: data/directories.dat is not a file

### ISSUE THREAD

**Issue by pharazone** [stanislav-web/OpenDoor#25]
I installed it on Global ,when I finished it, I typed "opendoor --version", and it showed this error "error:   PackageError: str: data/directories.dat is not a file".

![image](https://user-images.githubusercontent.com/11215634/43147502-c36d31c0-8f95-11e8-9926-d470b0dc2c35.png)

So how can I fix it. THX.

**Comment by stanislav-web** [comment]
Please install it directly from `git clone` ! I will resolve this problem later

**Comment by juanmera** [comment]
I'm having the same problem. I clone the repo and did the global installation. It only works when I run it from the repo directory (I guess it's trying to look for the data file in the directory where it's executed)

**Comment by SuperPHIJKLMNOP** [comment]
The solution I came up with is editing 

> 'data': {
        'directories': 'data/directories.dat',
        'ignored': 'data/ignored.dat',
        'proxies': 'data/proxies.dat',
        'subdomains': 'data/subdomains.dat',
        'useragents': 'data/useragents.dat',
        'tmplist': 'tmp/list.tmp',
        'extensionlist': 'tmp/extensionlist.tmp',
        'ignore_extensionlist': 'tmp/ignore_extensionlist.tmp',
        'reports': 'reports/',
        'exceptions_log': 'syslog/exceptions.log',
    }

In _**core.py**_ and giving the full path of each file: 

> 'data': {
        'directories': '/Users/xyz/Desktop/Autre/OpenDoor/data/directories.dat',
        'ignored': '/Users/xyz/Desktop/Autre/OpenDoor/data/ignored.dat',
        'proxies': '/Users/xyz/Desktop/Autre/OpenDoor/data/proxies.dat',
        'subdomains': '/Users/xyz/Desktop/Autre/OpenDoor/data/subdomains.dat',
        'useragents': '/Users/xyz/Desktop/Autre/OpenDoor/data/useragents.dat',
        'tmplist': 'tmp/list.tmp',
        'extensionlist': 'tmp/extensionlist.tmp',
        'ignore_extensionlist': 'tmp/ignore_extensionlist.tmp',
        'reports': 'reports/',
        'exceptions_log': 'syslog/exceptions.log',
    }

And then everything works fine :)
