### ISSUE TITLE
how to scan in a specific directory but not just in "/"

### ISSUE THREAD

**Issue by djerryz** [stanislav-web/OpenDoor#26]
eg.
 i want to scan in ip/hello/*
but when i input command: 
python3 opendoor.py --host ip/hello/ --port 80

the scanner just scan in directory "/"

**Comment by stanislav-web** [comment]
@djerrystyle currently its not available . 
P.S Marked this PR as `enhancement`

**Comment by stanislav-web** [comment]
@djerryz 
```
--prefix - append path prefix to scan host. Works for directories scan type

opendoor --host example.com --prefix en/
opendoor --host example.com --scan directories --prefix en/
```
