### ISSUE TITLE
[!] Several dependencies wasn't installed!

### ISSUE THREAD

**Issue by khairulreen** [stanislav-web/OpenDoor#27]
Hi, the dependencies already meet when I install them.

sudo pip install -r requirements.txt
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: json2html in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: tabulate in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))

But, I ran the script got error as the title

**Comment by stanislav-web** [comment]
Please use target installer `git clone`
