### ISSUE TITLE
[!] Several dependencies wasn't installed!

### ISSUE THREAD

**Issue by tacticthreat** [stanislav-web/OpenDoor#29]
root@kali:~/Tools/OpenDoor# pip install -r requirements.txt 
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.22)
Collecting json2html (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/23/33/e6367858c5da6795d3277e9ea4e58a70a7fd55f97f4bcc90b1ecec1c1410/json2html-1.2.1.tar.gz
Collecting tabulate (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 2.8MB/s 
Building wheels for collected packages: json2html, tabulate
  Running setup.py bdist_wheel for json2html ... done
  Stored in directory: /root/.cache/pip/wheels/c8/8a/ae/daa5ab4d808a6b7f77d8fd967efd85ccf2e18364ed87b0c694
  Running setup.py bdist_wheel for tabulate ... done
  Stored in directory: /root/.cache/pip/wheels/2a/85/33/2f6da85d5f10614cbe5a625eab3b3aebfdf43e7b857f25f829
Successfully built json2html tabulate
Installing collected packages: json2html, tabulate
Successfully installed json2html-1.2.1 tabulate-0.8.2
root@kali:~/Tools/OpenDoor# chmod +x opendoor.py 
root@kali:~/Tools/OpenDoor# python3 opendoor.py --host https://www.placeholder.org
		[!] Several dependencies wasn't installed!
            Please run sudo pip install -r requirements.txt 

root@kali:~/Tools/OpenDoor# sudo pip install -r requirements.txt 
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.22)
Requirement already satisfied: json2html in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: tabulate in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (0.8.2)
root@kali:~/Tools/OpenDoor# python3 opendoor.py --host https://www.placeholder.org
		[!] Several dependencies wasn't installed!

**Comment by stanislav-web** [comment]
Update please
