### ISSUE TITLE
not working issue

### ISSUE THREAD

**Issue by bishal0x01** [stanislav-web/OpenDoor#33]
Hello,
After successfully install requirements.txt I am getting the following error.
[!] Several dependencies wasn't installed!
            Please run sudo pip install -r requirements.txt 
How can I fix it?

**Comment by vizt3r** [comment]
same issue, hope someone know how to fix it..

**Comment by stanislav-web** [comment]
Currently installer has been updated. Please pull or update from opendor.py and writeback please which dependencies are not exists
