### ISSUE TITLE
Feature Request: Show only found items

### ISSUE THREAD

**Issue by random-robbie** [stanislav-web/OpenDoor#36]
Hey, 

could you add an option to only show found items or anything with 3xx or 2xx responses?

i know it currently shows some denied requests but sometimes that's not useful and only the 2xx or 3xx are handy to see.

**Comment by stanislav-web** [comment]
@random-robbie  use `--debug -1` to entrance into silent mode
https://github.com/stanislav-web/OpenDoor/pull/51
