### ISSUE TITLE
It's better to add encoding

### ISSUE THREAD

**Issue by WingMrL** [stanislav-web/OpenDoor#40]
https://github.com/stanislav-web/OpenDoor/blob/c5e271f5ff9d4373c1185d03e4fc54d19e4d4ed2/setup.py#L22

`LONG_DESCRIPTION = open('README.rst', 'r+', encoding='utf-8').read()`

**Comment by stanislav-dev** [comment]
Oke!

**Comment by stanislav-web** [comment]
Hi @WingMrL  
Added https://github.com/stanislav-web/OpenDoor/pull/52
