### ISSUE TITLE
Ignore invalid SSL certs

### ISSUE THREAD

**Issue by ghost** [stanislav-web/OpenDoor#44]
This tool is really great, but sometimes i need to test it against self signed certs or expired/invalid ones.
what about to add a flag to ignore invalid or self signed certs?

**Comment by stanislav-dev** [comment]
Great idea! I'll update it soon

**Comment by stanislav-web** [comment]
https://github.com/stanislav-web/OpenDoor/releases/tag/v.4.0.3 behavior was added by default
