### ISSUE TITLE
'Worker' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by sailawhk** [stanislav-web/OpenDoor#48]
What is the problem for this issue?
Thanks

**Comment by RinkuMeena** [comment]
I have same issue.

**Comment by dgrivera** [comment]
I have the same issue when running the command, and all installation are ok.

**Comment by stanislav-web** [comment]
@dgrivera solved https://github.com/stanislav-web/OpenDoor/pull/50
Please update application
