### ISSUE TITLE
HTTPConnection.__init__() got an unexpected keyword argument 'cert_reqs'

### ISSUE THREAD

**Issue by Pessword** [stanislav-web/OpenDoor#64]
zsh: terminated  python3 opendoor.py --host

What is the mistake i have done ?

**Comment by Pessword** [comment]
Done

**Comment by stanislav-web** [comment]
Will be. fixed during day.  It happened on HTTP requests only

**Comment by stanislav-web** [comment]
@Pessword  
https://github.com/stanislav-web/OpenDoor/releases/tag/v.4.0.61


v4.0.61 (30.06.2023)
Added +1007 directories
Optimize directories.txt list (sort, removed trash lines)
Fix https://github.com/stanislav-web/OpenDoor/issues/64 HTTPConnection.init() got an unexpected keyword argument 'cert_reqs'
