### ISSUE TITLE
not support https and not support redirect

### ISSUE THREAD

**Issue by potapo** [stanislav-web/OpenDoor#7]
redirect=False 时候，redirecct才会加入列表。。。。。不支持https，不支持http port。。。。。不支持http复用。不过程序架构不错，赞一个👍一个

**Comment by stanislav-web** [comment]
I'll do it later

**Comment by stanislav-web** [comment]
Added HTTPS support

**Comment by stanislav-web** [comment]
Added redirect detection and follows. Testing please

**Comment by attacker212** [comment]
It detects the redirect but still provides with false positives.
